services:
  primitiveapi:
    image: primitiveapi
    container_name: app
    build:
      context: .
      dockerfile: PrimitiveApi/Dockerfile
    environment:
      TELEGRAM_BOT_TOKEN : ${TELEGRAM_BOT_TOKEN}
      CONNECTION_STRING: "Host=db;Port=5432;Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};Database=${POSTGRES_DB};"
    ports:
      - 5000:5000
      - 5001:5001
    networks:
      - my-network
      
  db:
    image: postgres
    container_name: database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB}
      POSTGRES_DB: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    networks:
      - my-network
    volumes:
      - ./db:/var/lib/postgresql/data
      
networks:
  my-network:
    driver: bridge